import Head from 'next/head';
import { Header } from '../components';

export default function Home() {
  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* SideBar */}

      {/* Feed */}

      {/* Widgets */}
    </div>
  );
}
